language: python
python:
- '3.6'
sudo: required
services:
- docker
script:
- 
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
env:
  global:
  - secure: qUvjO3EIB8rAPp+38dklj6e7KJuEvQlv2OJV+NVVRZZXJdDxCZYgn3ydtSmJ2PhqPlKguH9Te5JeRGQkV5zIAUQ6q8D9dkFEexkJvsRQ3Y7fMyjqIWUWLVr/99XVLdpeMAEdqoL+AfB17vPWChvV/0nKC098FjiFjOqOoArr9N4dozCCYfgQRzQEFbgBzAVMeyAxIrTkOC5pb7uv8yVqZVdyE+Im0Ux0ekG6EQ2sBogrPwyjGgxHxK2IpJvoBtLSUf631xckK03Q16ckLkLoDdvI/LTYErJdSUUM/wi0wlANfwz6A/kV1ZllIYYEy9hRBi6Hq3I49Ehvo9Jlcue7jeRDhWdZyz8jEvfo7YbVY/jR9sgJ5vULAG6hNe0r9UJsFJj3i2mJ5breFt9i4WpP6qu/6bGatXxx0Yuki5TTYZ+jpBAnXKdaYcR2hMcBYLRfzjzr/3gLp1Hc1DY1gv2x+56XHQIMhQVSnpFHq7e6WlRokCrv9rsOCvM1gg8p/evqt5GsNehjgMZPoVGdmibChPosWoU0vP+TM7m7jW6X74yHjzkIUJtUgPsYlqoEy0WKzw0717twJD+ViMNtSMvcc+96aqfs/WaKUK7EUT3DZDJtuL6IYfWqbDDvdYduAY6AAsnHmWFceeM+bz2UoExiNVcWM8qaZuhQ2vD54WoITJ8=
  - secure: bL5gKcbOYi91zdtmw2BoqfLd54JGHx+emLwhh6sFGjvwzEs4aqN7cyZOcCtHeveiRyKJQps5n64gcGhOBQf+Qtk3V+sbQd7GU2aRvpbjc9kgaPzHGG3m2kMX4FFkFtZhaE2QsmBlE7RfR2AfhDq2Z/sY/kZiV+3x80Je3OIYKzsgdVpd08YBDcT31gdlLJCK/TquDEMawyI9qoNjH8ljImaCJ7UZUGDEI6+yvSpOi8+QPq3UUzD2Ek7q063VacNo0HP32xdoFn+TBN0GQlKUH84KqXrs607zr8lFeKDifik3QzVekvPKulLD83NNMgKl4qOq+hx3uGmUPAdWxXdfVJPJ4dNOPN2g6UZuydM/5AIpEQRXDW2SvfalSJpCmpwxrRKUrIllCD7OG2BZCZHvFIv6I54pXfqm4toTiQNJxLoQ3hyfsAhpmQWd27ZVcPMoxW++mOwn+KR5HROwliOFEGRijdhx3xBIQHRV8DifCAfHRoaLoAV3Chla9UdbO26NqPAfPNROgmuzvPW25gEagny175WhhIG24S0lDHf9mvdl4KlWI40CwKpAFZ0VGnaS8OIFsyGjoPd2B94RWeoPryUOZX9ChqsI9ND5P8WopvROJb/kOb77h3jJjyb2aqPqUTDBi9gTJe4hONnViV2XFei5P8y2whYrqoXx+0yzRYM=
